version: "3.8"

services:
    app:
        build:
            context: .
        environment:
            MONGO_URI: mongodb://mongo/node_ts_poc
            JWT_SECRET: thomas-anderson-neo
            PORT: 4000
        depends_on:
            - mongo
        ports:
            - '4000:4000'

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - data-volume:/data/db

volumes:
    data-volume: